package http

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	_ "github.com/rogerio-castellano/inventory-tracker/api/docs" // generated by swag
	"github.com/rogerio-castellano/inventory-tracker/internal/http/handlers"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func NewRouter() http.Handler {
	r := chi.NewRouter()
	r.Get("/products", handlers.GetProductsHandler)

	r.Get("/products/{id}", handlers.GetProductByIDHandler)
	r.Get("/products/filter", handlers.FilterProductsHandler)

	r.Get("/products/{id}/movements", handlers.GetMovementsHandler)
	r.Get("/products/{id}/movements/export", handlers.ExportMovementsHandler)

	r.Post("/login", handlers.LoginHandler)
	r.Post("/register", handlers.RegisterHandler)

	r.Route("/metrics", func(r chi.Router) {
		r.Use(AuthMiddleware, RequireRole("admin"))
		r.Get("/dashboard", handlers.GetDashboardMetricsHandler)
	})

	r.Group(func(r chi.Router) {
		r.Use(AuthMiddleware)

		r.Post("/products", handlers.CreateProductHandler)
		r.Put("/products/{id}", handlers.UpdateProductHandler)
		r.Delete("/products/{id}", handlers.DeleteProductHandler)
		r.Post("/products/{id}/adjust", handlers.AdjustQuantityHandler)
		r.Post("/products/import", handlers.ImportProductsHandler)

		r.Post("/logout", handlers.LogoutHandler)
		r.Post("/logout/all", handlers.LogoutAllHandler)
	})

	r.Route("/admin", func(r chi.Router) {
		r.Use(AuthMiddleware, RequireRole("admin"))
		r.Post("/users", handlers.RegisterAsAdminHandler)
		r.Get("/users/{username}/tokens", handlers.ListUserTokensHandler)
		r.Get("/tokens", handlers.ListRefreshTokensHandler)
		r.Delete("/tokens/{username}", handlers.RevokeRefreshTokenHandler)
	})

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), //The url pointing to API definition
	))

	r.With(AuthMiddleware).Get("/me", handlers.MeHandler)

	r.Post("/refresh", handlers.RefreshHandler)

	return r
}
