package http

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	_ "github.com/rogerio-castellano/inventory-tracker/api/docs" // generated by swag
	"github.com/rogerio-castellano/inventory-tracker/internal/http/handlers"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func NewRouter() http.Handler {
	r := chi.NewRouter()
	r.Get("/products", handlers.GetProductsHandler)

	r.Get("/products/{id}", handlers.GetProductByIDHandler)
	r.Get("/products/filter", handlers.FilterProductsHandler)

	r.Get("/products/{id}/movements", handlers.GetMovementsHandler)
	r.Get("/products/{id}/movements/export", handlers.ExportMovementsHandler)

	r.Post("/login", handlers.LoginHandler)
	r.Post("/register", handlers.RegisterHandler)

	r.Get("/metrics/dashboard", handlers.GetDashboardMetricsHandler)

	r.Group(func(protected chi.Router) {
		protected.Use(AuthMiddleware)

		protected.Post("/products", handlers.CreateProductHandler)
		protected.Put("/products/{id}", handlers.UpdateProductHandler)
		protected.Delete("/products/{id}", handlers.DeleteProductHandler)
		protected.Post("/products/{id}/adjust", handlers.AdjustQuantityHandler)
		protected.Post("/products/import", handlers.ImportProductsHandler)
	})

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), //The url pointing to API definition
	))

	return r
}
