package router

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	_ "github.com/rogerio-castellano/inventory-tracker/api/docs" // generated by swag
	"github.com/rogerio-castellano/inventory-tracker/internal/http/handlers"
	mw "github.com/rogerio-castellano/inventory-tracker/internal/http/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func NewRouter() http.Handler {
	r := chi.NewRouter()
	r.Get("/products", handlers.GetProductsHandler)

	r.Get("/products/{id}", handlers.GetProductByIDHandler)
	r.Get("/products/filter", handlers.FilterProductsHandler)

	r.Get("/products/{id}/movements", handlers.GetMovementsHandler)
	r.Get("/products/{id}/movements/export", handlers.ExportMovementsHandler)

	r.With(mw.RedisRateLimitPerRole("login")).Post("/login", handlers.LoginHandler)
	r.With(mw.RateLimitMiddleware).Post("/register", handlers.RegisterHandler)

	r.Route("/metrics", func(r chi.Router) {
		r.Use(mw.AuthMiddleware, mw.RequireRole("admin"))
		r.Get("/dashboard", handlers.GetDashboardMetricsHandler)
	})

	r.With(mw.RedisRateLimitPerRole("refresh")).Post("/refresh", handlers.RefreshHandler)

	r.Group(func(r chi.Router) {
		r.Use(mw.AuthMiddleware)

		r.Post("/products", handlers.CreateProductHandler)
		r.Put("/products/{id}", handlers.UpdateProductHandler)
		r.Delete("/products/{id}", handlers.DeleteProductHandler)
		r.Post("/products/{id}/adjust", handlers.AdjustQuantityHandler)
		r.Post("/products/import", handlers.ImportProductsHandler)

		r.Post("/logout", handlers.LogoutHandler)
		r.Post("/logout/all", handlers.LogoutAllHandler)

		r.Get("/me", handlers.MeHandler)
	})

	r.Route("/admin", func(r chi.Router) {
		r.Use(mw.AuthMiddleware, mw.RequireRole("admin"))
		r.Post("/users", handlers.RegisterAsAdminHandler)
		r.Get("/tokens", handlers.ListRefreshTokensHandler)
		r.Delete("/tokens/{username}", handlers.RevokeRefreshTokenHandler)
		r.Get("/users/{username}/tokens", handlers.ListUserTokensHandler)
		r.Delete("/users/{username}/tokens", handlers.RevokeAllUserSessionsHandler)
		r.Delete("/users/{username}/tokens/{sessionKey}", handlers.RevokeUserSessionHandler)
		r.With(mw.RedisRateLimitPerRole("admin-impersonate")).Post("/users/{username}/tokens", handlers.AdminImpersonateUserHandler)
		r.Get("/bans", handlers.ListActiveBansHandler)
		r.Delete("/bans/{id}", handlers.UnbanHandler)
		r.Post("/bans/summary/send", handlers.TriggerDailyBanSummaryHandler)
	})

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), //The url pointing to API definition
	))

	return r
}
