development:
  dialect: postgres
  database: inventory
  user: postgres
  password: example
  host: localhost
  port: 5432

tests:
  dialect: postgres
  database: inventory_tests
  user: postgres
  password: example
  host: localhost
  port: 5432
