services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.env
    container_name: inventory-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/inventory?sslmode=disable
      ALERT_FROM: james.smith@smith.com
      ALERT_TO: john.johnson@johnson.com
      SMTP_SERVER: mailhog
      SMTP_PORT: 1025
      SMTP_USER: test
      SMTP_PASS: test
      SMTP_AUTH_DISABLED: yes

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-dev
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_AUTH_FILE: /mailhog.auth
      MH_MAILDIR_PATH: /data
      MH_STORAGE: maildir
    volumes:
      - ./mailhog.auth:/mailhog.auth:ro
      - ./data:/data:rw
volumes:
  pgdata:
