services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.fast
    container_name: inventory-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/inventory?sslmode=disable

volumes:
  pgdata:
