@url=http://localhost:8080

# Valid product creation
POST {{url}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "Book",
    "price": 1.23,
    "quantity": 1
}

###

GET {{url}}/products HTTP/1.1

###

GET {{url}}/products/1 HTTP/1.1

###

DELETE {{url}}/products/3 HTTP/1.1

###

PUT {{url}}/products/2 HTTP/1.1
Content-Type: application/json

{
    "id" : 2,
    "name": "Go",
    "price": 4.44,
    "quantity": 4
}

### Filter products
GET {{url}}/products/filter?name=o&minQty=2&maxQty=4&minPrice=1&maxPrice=4.44 HTTP/1.1

###
GET {{url}}/products/filter?offset=1&limit=2 HTTP/1.1


### Adjust quantity
POST {{url}}/products/4/adjust HTTP/1.1
Content-Type: application/json

{
    "delta": 2
}

### 
POST {{url}}/products/4/adjust HTTP/1.1
Content-Type: application/json

{
    "delta": -2
}

###
POST {{url}}/products/4/adjust HTTP/1.1
Content-Type: application/json

{
    "delta": -100
}

### 
POST {{url}}/products/1000/adjust HTTP/1.1
Content-Type: application/json

{
    "delta": -2
}

###
GET {{url}}/products/4/movements HTTP/1.1

###
GET {{url}}/products/4/movements?since=2025-07-03T19:50:00Z&until=2025-07-04T00:31:36Z HTTP/1.1

###
GET {{url}}/products/4/movements?offset=1&limit=2 HTTP/1.1

###
GET {{url}}/products/4/movements?limit=1 HTTP/1.1

### Movements with zero limit should return only meta data
GET {{url}}/products/4/movements?limit=0 HTTP/1.1

### Movements with invalid product ID
GET {{url}}/products/1000/movements HTTP/1.1

### Movements with invalid since date
GET {{url}}/products/4/movements?since=invalid-date&until=2025-07-04T00:31:36Z HTTP/1.1

### Movements with invalid until date
GET {{url}}/products/4/movements?since=2025-07-03T19:50:00Z&until=invalid-date HTTP/1.1

### Movements with invalid limit
GET {{url}}/products/4/movements?limit=invalid HTTP/1.1

### Movements with invalid offset
GET {{url}}/products/4/movements?offset=invalid HTTP/1.1

### Movements with negative limit
GET {{url}}/products/4/movements?limit=-1 HTTP/1.1

### Movements with negative offset
GET {{url}}/products/4/movements?offset=-1 HTTP/1.1

### Movements with zero offset (should return all)
GET {{url}}/products/4/movements?offset=0 HTTP/1.1

### Movements with limit greater than total count (should use the default limit instead)
GET {{url}}/products/4/movements?limit=100 HTTP/1.1

### Movements with large offset (should return only meta data)
GET {{url}}/products/4/movements?offset=1000 HTTP/1.1

### 


