@url=http://localhost:8080

# Valid product creation
POST {{url}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "Book",
    "price": 1.23,
    "quantity": 1
}

###

GET {{url}}/products HTTP/1.1

###

GET {{url}}/products/1 HTTP/1.1

###

DELETE {{url}}/products/3 HTTP/1.1

###

PUT {{url}}/products/2 HTTP/1.1
Content-Type: application/json

{
    "id" : 2,
    "name": "Go",
    "price": 4.44,
    "quantity": 4
}