@url=http://localhost:8080

# Replace below with loginUserRole and run this request to test with unauthorized role
@token={{loginAdminRole.response.body.$.token}}

# Login with admin role credentials (authorized)
# @name loginAdminRole
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "secret"
}

### Login with user role credentials (unauthorized)
# @name loginUserRole
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username" : "rogerio",
    "password": "very-secret"
}

###
GET {{url}}/metrics/dashboard HTTP/1.1
Authorization: Bearer {{token}}
