@url=http://localhost:8080
# Run the login request at the bottom of this file (@name login) to obtain the auth token
@token={{login.response.body.$.access_token}}

### Valid product creation

POST {{url}}/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "100 Go Mistakes and How to Avoid Them",
    "price": 12.34,
    "quantity": 10,
    "threshold": 5
}

###
GET {{url}}/products HTTP/1.1

###
GET {{url}}/products/1 HTTP/1.1

###
DELETE {{url}}/products/5 HTTP/1.1
Authorization: Bearer {{token}}

###
PUT {{url}}/products/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Go Programming Language",
    "price": 11.11,
    "quantity": 11,
    "threshold": 12
}

### Filter products
GET {{url}}/products/filter?name=o&minQty=1&maxQty=40&minPrice=1&maxPrice=20 HTTP/1.1

GET {{url}}/products/filter?name=o&minQty=2&maxQty=4&minPrice=1&maxPrice=4.44 HTTP/1.1

###
GET {{url}}/products/filter?offset=1&limit=2 HTTP/1.1

###
POST http://localhost:8080/products/import
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="products.csv"
Content-Type: text/csv

< ./products.csv
--boundary--



###
# Login with valid credentials (keep it after business endpoints)
# @name login
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "secret"
}
