@url=http://localhost:8080
# Run the login request at the bottom of this file (@name login) to obtain the auth token
@token={{login.response.body.$.token}}

###
POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "username" : "rogerio",
    "password": "very-secret"
}

###
POST {{url}}/admin/users HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username" : "adrian",
    "password": "top-secret",
    "role": "admin"
}

###
GET {{url}}/me HTTP/1.1
Authorization: Bearer {{token}}


###
# Login with valid credentials (keep it after business endpoints)
# @name login
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "secret"
}
